# This Dockerfile was based on: 
# https://towardsdatascience.com/deploying-python-script-to-docker-container-and-connect-to-external-sql-server-in-10-minutes-225ff4c19ce5
FROM mcr.microsoft.com/mssql-tools

WORKDIR /app
ADD  . .

CMD ["sleep", "infinity"]